name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Blazor WebAssembly App
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./RioTintoApp/Client/RioTintoApp.Client.csproj

      # Step 4: Build the Blazor WebAssembly application
      - name: Build the app
        run: dotnet publish ./RioTintoApp/Client/RioTintoApp.Client.csproj -c Release -o ./RioTintoApp/Client/build

      # Step 5: Debugging - List build directory
      - name: Debug: List contents of build/wwwroot
        run: ls -R ./RioTintoApp/Client/build/wwwroot

      # Step 6: Debugging - Check for default files
      - name: Debug: Check for default files
        run: |
          if [ ! -f ./RioTintoApp/Client/build/wwwroot/index.html ]; then
            echo "Error: index.html not found in build/wwwroot"
            exit 1
          fi

      # Step 7: Deploy to Azure Static Web Apps
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: './RioTintoApp/Client/build/wwwroot'
          skip_app_build: true
