name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Hosted Blazor WebAssembly App
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Update this to match your .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./RioTintoApp.Server/RioTintoApp.Server.csproj

      # Build the application
      - name: Build the app
        run: dotnet publish ./RioTintoApp.Server/RioTintoApp.Server.csproj -c Release -o output

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: './output/wwwroot' # Path to the server's published wwwroot folder
          skip_app_build: true
