name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Hosted Blazor WebAssembly App
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Update this if you're using a different .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./RioTintoApp/Client/RioTintoApp.Client.csproj

      # Build the Blazor WebAssembly application
      - name: Build the app
        run: dotnet publish ./RioTintoApp/Client/RioTintoApp.Client.csproj -c Release -o build

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: './RioTintoApp/Client/wwwroot'  # Path to the built app containing index.html
          skip_app_build: true

      #    app_location: './RioTintoApp.Client/build/wwwroot' # Path to the built app containing index.html
      #    skip_app_build: true
